### ISSUE TITLE
Migration db exception :The method or operation is not implement

### ISSUE THREAD

**Issue by zzyykk123456** [si2030/Asp.net-Core-2-React-Redux-using-Javascriptservices#1]
when i migration db,experiencing a problem.what should I do?
![default](https://user-images.githubusercontent.com/12078303/30626985-223acad8-9e00-11e7-800f-4e0aff2bf09d.png)

**Comment by si2030** [comment]
I upgraded this project to Asp.net Core 2 and then got problems even creating a migration. I can now delete the migration folder and get the entity framework to recreate it but now its more difficult than before. With regard to the context its located in JobsLedger.DATA and it called "JobsLedgerAPIContext". So what you can do is delete the migrations folder and then I do the following:

(NOTE - I havent created a Migrations.cs file in this solution but I will in a future update however its below.

To create a migrations.cs file using Enitiy Framework Core 2 you have to do the following - From the project directory where your context resides - in this case JobsLedger.DATA - you have to....

1) create the following migrations.cs file (just need to do this once). This has to be in the API project - Thats JobsLedger.API

using JobsLedger.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace JobsLedger.API
{
    public class DesignTimeDbContextFactory : IDesignTimeDbContextFactory<JobsLedgerAPIContext>
    {
        public JobsLedgerAPIContext CreateDbContext(string[] args)
        {
            IConfigurationRoot configuration = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json")
                .Build();

            var builder = new DbContextOptionsBuilder<JobsLedgerAPIContext>();

            var connectionString = configuration.GetConnectionString("DefaultConnection");

            builder.UseSqlServer(connectionString);

            return new JobsLedgerAPIContext(builder.Options);
        }
    }
}

2) navigate to the same directory as the dbcontext file resides. In the case its JobsLedger.DATA folder and in a command line you do the following. (open cmd in the JobsLedger.DATA folder)

3) RUN THE FOLLOWING:

dotnet ef migrations add InitialMigration -s ../JobsLedger.API

dotnet ef database update -s ../JobsLedger.API

"-s" is the startup project.

**Comment by zzyykk123456** [comment]
@si2030 Thanks for response.It works.

**Comment by si2030** [comment]
Closed..

**Comment by zzyykk123456** [comment]
@si2030  I do some changes.I edit your Program.cs in JobsLedger.DATA(Dont have to add migrations.cs  in JobsLedger.API). Generally ,JobsLedger.DATA depends on appsettings.json(It's in JobsLedger.API),so the startup project is JobsLedger.API.In fact,It's the same to your migrations.cs.Ha-ha.
![default](https://user-images.githubusercontent.com/12078303/30632942-6869e5fe-9e1c-11e7-954e-8206d73cb2a5.png)
